version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}-nginx
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html
  php:
    image: php:fpm
    container_name: ${APP_NAME}-php-fpm
    ports:
      - 9000:9000
    volumes:
      - ./:/usr/share/nginx/html
  mysql:
    image: mysql:latest
    container_name: ${APP_NAME}-mysql
    ports:
      - 3306:3306
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: b1sm1ll4h
      MYSQL_DATABASE: ppdb
